apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner
  namespace: gitea-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Показывает, что раннеру необходимы права администратора для сборки k8s манифестов
subjects:
- kind: ServiceAccount
  name: gitea-runner
  namespace: gitea-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
spec:
  replicas: 2 # Изменено на 2 для демонстрации масштабируемости под задачи параллельной сборки
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      serviceAccountName: gitea-runner
      containers:
      - name: runner
        image: gitea/act_runner:latest
        env:
        - name: GITEA_INSTANCE_URL
          value: "https://gitea.example.edu.kz"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-runner-secret
              key: registration_token # Сам секрет безопасно извлекается из K8s Secret
        - name: GITEA_RUNNER_NAME
          value: "k8s-shared-runner"
        - name: CONFIG_FILE
          value: /config.yaml
        volumeMounts:
        - name: config
          mountPath: /config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: gitea-runner-config